name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Running this job only for master branch
    steps:
      - uses: actions/checkout@v4 # Checking out the repo
      - name: Build and Publish latest Docker image
        uses: TCPShield/gp-docker-action@1.1.13
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: ghcr.io/setnemo/php:latest # Provide Docker image name
          image-tag: latest # Provide Docker image tag
